# 项目端口号
server:
  port: 8001

# 项目名称
spring:
  application:
    name: cloud-payment-service
  # mysql 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Dosea0118
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.enn.entities
